/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "ewecpcsonrsizosnbyuk"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV3ZWNwY3NvbnJzaXpvc25ieXVrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjgzMzI2NjMsImV4cCI6MjA4MzkwODY2M30.CHHqgJHp-R-h5BIa828vVUE2Q8Yg9pFme8GtKYgt4Kk"